library (datasets)
data (iris)
names (iris)
summary (iris)
summary (iris$Sepal.Width)
View(iris)
is.na(iris$Sepal.Width)
length(unique(iris$Sepal.Width))
plot(iris)
plot(iris$Petal.Width, iris$Petal.Length)